started
vud531/React-UI-Components pull request #1
Opened 2019-03-18 23:40 UTC by vud531

2019-03-19 17:07 UTC, NickStrick requested changes
make sure you give me more commits 😠 these make easier to looks at and review your code, and also makes your github look better.
these concepts are important to everything were doing this month so i encourage you to go back and complete this, but current lessons and projects take priority over missed projects.

2019-03-20 17:16 UTC, NickStrick approved these changes
looks great! great use of props and components, demonstrates a good understanding of the material so far, but dont allow that to be an excuse to be lazy, repetition is the key to a strong foundation in learning new concepts

2019-03-20 17:16 UTC, NickStrick commented on Project-II-Calculator/calculator/src/App.js
> +function onClickHandler(e) {
wow awesome looking stretch great job on getting these handlers started.

2019-03-20 17:16 UTC, NickStrick commented on Project-II-Calculator/calculator/src/App.js
> +document.addEventListener('click', (e) => onClickHandler(e) );
so in react we can add an onClick property to our html tags and just pass the function into them inside our child components that your returning in your .map function.

i encourage you to take a look at that:
https://reactjs.org/docs/handling-events.html

2019-03-20 17:16 UTC, merged

2019-03-20 21:48 UTC, vud531 commented
> looks great! great use of props and components, demonstrates a good understanding of the material so far, but dont allow that to be an excuse to be lazy, repetition is the key to a strong foundation in learning new concepts



> looks great! great use of props and components, demonstrates a good understanding of the material so far, but dont allow that to be an excuse to be lazy, repetition is the key to a strong foundation in learning new concepts

Thanks for the feedback! By the way, I'm not being lazy, I just have a lot to prioritize, so I got worked up by the end of the day, and lost focus a little. But, I always have a plan to get back on track. I just don't communicate that relly well.